apiVersion: apps/v1
kind: Deployment
metadata:
  name: attendees-api-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attendees-api
      version: v1
  template:
    metadata:
      labels:
        app: attendees-api
        version: v1
    spec:
      containers:
        - name: attendees
          image: jpgough/attendees:v1
          ports:
            - containerPort: 8080
            - containerPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: attendees-api-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attendees-api
      version: v2
  template:
    metadata:
      labels:
        app: attendees-api
        version: v2
    spec:
      containers:
        - name: attendees
          image: jpgough/attendees:v2
          ports:
            - containerPort: 8080
            - containerPort: 9090